# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 331)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Painel1 = QtWidgets.QFrame(self.centralwidget)
        self.Painel1.setGeometry(QtCore.QRect(0, 0, 501, 321))
        self.Painel1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Painel1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Painel1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Painel1.setObjectName("Painel1")
        self.R_cliente = QtWidgets.QPushButton(self.Painel1)
        self.R_cliente.setGeometry(QtCore.QRect(120, 10, 251, 41))
        self.R_cliente.setStyleSheet("background-color: rgb(147, 147, 147);\n"
"border-radius: 10px;\n"
"border-radius: 10px;\n"
"font-family: arial;\n"
"font-size:14px;\n"
"text-transform: uppercase;\n"
"font-weight:700;\n"
"")
        self.R_cliente.setObjectName("R_cliente")
        self.R_pecas = QtWidgets.QPushButton(self.Painel1)
        self.R_pecas.setGeometry(QtCore.QRect(120, 60, 251, 41))
        self.R_pecas.setStyleSheet("background-color: rgb(147, 147, 147);\n"
"border-radius: 10px;\n"
"border-radius: 10px;\n"
"font-family: arial;\n"
"font-size:14px;\n"
"text-transform: uppercase;\n"
"font-weight:700;\n"
"")
        self.R_pecas.setObjectName("R_pecas")
        self.L_pecas = QtWidgets.QPushButton(self.Painel1)
        self.L_pecas.setGeometry(QtCore.QRect(120, 110, 251, 41))
        self.L_pecas.setStyleSheet("background-color: rgb(147, 147, 147);\n"
"border-radius: 10px;\n"
"border-radius: 10px;\n"
"font-family: arial;\n"
"font-size:14px;\n"
"text-transform: uppercase;\n"
"font-weight:700;\n"
"")
        self.L_pecas.setObjectName("L_pecas")
        self.F_pedido = QtWidgets.QPushButton(self.Painel1)
        self.F_pedido.setGeometry(QtCore.QRect(120, 160, 251, 41))
        self.F_pedido.setStyleSheet("background-color: rgb(147, 147, 147);\n"
"border-radius: 10px;\n"
"border-radius: 10px;\n"
"font-family: arial;\n"
"font-size:14px;\n"
"text-transform: uppercase;\n"
"font-weight:700;\n"
"")
        self.F_pedido.setObjectName("F_pedido")
        self.R_conta = QtWidgets.QPushButton(self.Painel1)
        self.R_conta.setGeometry(QtCore.QRect(120, 210, 251, 41))
        self.R_conta.setStyleSheet("background-color: rgb(147, 147, 147);\n"
"border-radius: 10px;\n"
"border-radius: 10px;\n"
"font-family: arial;\n"
"font-size:14px;\n"
"text-transform: uppercase;\n"
"font-weight:700;\n"
"")
        self.R_conta.setObjectName("R_conta")
        self.PR_pecas = QtWidgets.QFrame(self.centralwidget)
        self.PR_pecas.setGeometry(QtCore.QRect(0, 0, 501, 321))
        self.PR_pecas.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.PR_pecas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PR_pecas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PR_pecas.setObjectName("PR_pecas")
        self.label = QtWidgets.QLabel(self.PR_pecas)
        self.label.setGeometry(QtCore.QRect(10, 10, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.PR_pecas)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.PR_pecas)
        self.label_3.setGeometry(QtCore.QRect(10, 40, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.PR_pecas)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.PR_pecas)
        self.label_5.setGeometry(QtCore.QRect(10, 130, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.Pecas = QtWidgets.QLineEdit(self.PR_pecas)
        self.Pecas.setGeometry(QtCore.QRect(43, 10, 194, 20))
        self.Pecas.setObjectName("Pecas")
        self.M_D_Moto = QtWidgets.QLineEdit(self.PR_pecas)
        self.M_D_Moto.setGeometry(QtCore.QRect(106, 39, 131, 20))
        self.M_D_Moto.setObjectName("M_D_Moto")
        self.Preco = QtWidgets.QLineEdit(self.PR_pecas)
        self.Preco.setGeometry(QtCore.QRect(50, 70, 187, 20))
        self.Preco.setObjectName("Preco")
        self.Part = QtWidgets.QLineEdit(self.PR_pecas)
        self.Part.setGeometry(QtCore.QRect(67, 99, 170, 20))
        self.Part.setObjectName("Part")
        self.Mao_O = QtWidgets.QLineEdit(self.PR_pecas)
        self.Mao_O.setGeometry(QtCore.QRect(86, 130, 151, 20))
        self.Mao_O.setObjectName("Mao_O")
        self.BTT_peca = QtWidgets.QPushButton(self.PR_pecas)
        self.BTT_peca.setGeometry(QtCore.QRect(140, 220, 201, 41))
        self.BTT_peca.setStyleSheet("background-color: rgb(147, 147, 147);\n"
"border-radius: 10px;\n"
"font-family: arial;\n"
"font-size:14px;\n"
"text-transform: uppercase;\n"
"font-weight:700;\n"
"\n"
"")
        self.BTT_peca.setObjectName("BTT_peca")
        self.label_6 = QtWidgets.QLabel(self.PR_pecas)
        self.label_6.setGeometry(QtCore.QRect(10, 160, 67, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.spinTot = QtWidgets.QSpinBox(self.PR_pecas)
        self.spinTot.setGeometry(QtCore.QRect(79, 158, 159, 22))
        self.spinTot.setMinimum(1)
        self.spinTot.setMaximum(1000)
        self.spinTot.setObjectName("spinTot")
        self.Exit = QtWidgets.QPushButton(self.centralwidget)
        self.Exit.setGeometry(QtCore.QRect(470, 0, 21, 23))
        self.Exit.setStyleSheet("background-color: rgb(154, 6, 6);\n"
"border-radius: 10px;\n"
"font-family: arial;\n"
"font-size:14px;\n"
"text-transform: uppercase;\n"
"font-weight:700;\n"
"\n"
"")
        self.Exit.setObjectName("Exit")
        self.PL_pecas = QtWidgets.QFrame(self.centralwidget)
        self.PL_pecas.setGeometry(QtCore.QRect(0, 0, 501, 321))
        self.PL_pecas.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.PL_pecas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PL_pecas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PL_pecas.setObjectName("PL_pecas")
        self.Ver_Detalhe = QtWidgets.QPushButton(self.PL_pecas)
        self.Ver_Detalhe.setGeometry(QtCore.QRect(70, 260, 131, 31))
        self.Ver_Detalhe.setStyleSheet("background-color: rgb(147, 147, 147);\n"
"border-radius: 10px;\n"
"font-family: arial;\n"
"font-size:14px;\n"
"text-transform: uppercase;\n"
"font-weight:700;\n"
"")
        self.Ver_Detalhe.setObjectName("Ver_Detalhe")
        self.Excluir = QtWidgets.QPushButton(self.PL_pecas)
        self.Excluir.setGeometry(QtCore.QRect(270, 260, 131, 31))
        self.Excluir.setStyleSheet("background-color: rgb(147, 147, 147);\n"
"border-radius: 10px;\n"
"border-radius: 10px;\n"
"font-family: arial;\n"
"font-size:14px;\n"
"text-transform: uppercase;\n"
"font-weight:700;\n"
"")
        self.Excluir.setObjectName("Excluir")
        self.listPecas = QtWidgets.QListWidget(self.PL_pecas)
        self.listPecas.setGeometry(QtCore.QRect(2, 0, 431, 231))
        self.listPecas.setObjectName("listPecas")
        self.CH_M_D_O = QtWidgets.QCheckBox(self.PL_pecas)
        self.CH_M_D_O.setGeometry(QtCore.QRect(356, 233, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.CH_M_D_O.setFont(font)
        self.CH_M_D_O.setObjectName("CH_M_D_O")
        self.D_Pecas = QtWidgets.QFrame(self.centralwidget)
        self.D_Pecas.setGeometry(QtCore.QRect(-1, -1, 501, 321))
        self.D_Pecas.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.D_Pecas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.D_Pecas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.D_Pecas.setObjectName("D_Pecas")
        self.Dinhero_final = QtWidgets.QLabel(self.D_Pecas)
        self.Dinhero_final.setGeometry(QtCore.QRect(400, 292, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.Dinhero_final.setFont(font)
        self.Dinhero_final.setObjectName("Dinhero_final")
        self.Detalhes_peca = QtWidgets.QGroupBox(self.D_Pecas)
        self.Detalhes_peca.setGeometry(QtCore.QRect(10, 10, 231, 151))
        self.Detalhes_peca.setObjectName("Detalhes_peca")
        self.D_Peca = QtWidgets.QLabel(self.Detalhes_peca)
        self.D_Peca.setGeometry(QtCore.QRect(6, 23, 181, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.D_Peca.setFont(font)
        self.D_Peca.setObjectName("D_Peca")
        self.D_Modelo = QtWidgets.QLabel(self.Detalhes_peca)
        self.D_Modelo.setGeometry(QtCore.QRect(6, 44, 181, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.D_Modelo.setFont(font)
        self.D_Modelo.setObjectName("D_Modelo")
        self.D_Dispo = QtWidgets.QLabel(self.Detalhes_peca)
        self.D_Dispo.setGeometry(QtCore.QRect(7, 65, 181, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.D_Dispo.setFont(font)
        self.D_Dispo.setObjectName("D_Dispo")
        self.D_Preco = QtWidgets.QLabel(self.Detalhes_peca)
        self.D_Preco.setGeometry(QtCore.QRect(7, 86, 181, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.D_Preco.setFont(font)
        self.D_Preco.setObjectName("D_Preco")
        self.D_Part = QtWidgets.QLabel(self.Detalhes_peca)
        self.D_Part.setGeometry(QtCore.QRect(7, 110, 181, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.D_Part.setFont(font)
        self.D_Part.setObjectName("D_Part")
        self.BTT_A_Vista = QtWidgets.QPushButton(self.D_Pecas)
        self.BTT_A_Vista.setGeometry(QtCore.QRect(60, 230, 181, 41))
        self.BTT_A_Vista.setStyleSheet("background-color: rgb(147, 147, 147);\n"
"border-radius: 10px;\n"
"font-family: arial;\n"
"font-size:14px;\n"
"text-transform: uppercase;\n"
"font-weight:700;\n"
"\n"
"\n"
"\n"
"")
        self.BTT_A_Vista.setObjectName("BTT_A_Vista")
        self.BTT_Fiado = QtWidgets.QPushButton(self.D_Pecas)
        self.BTT_Fiado.setGeometry(QtCore.QRect(270, 230, 181, 41))
        self.BTT_Fiado.setStyleSheet("background-color: rgb(147, 147, 147);\n"
"border-radius: 10px;\n"
"font-family: arial;\n"
"font-size:14px;\n"
"text-transform: uppercase;\n"
"font-weight:700;\n"
"\n"
"")
        self.BTT_Fiado.setObjectName("BTT_Fiado")
        self.Lista_de_pessoas = QtWidgets.QListWidget(self.D_Pecas)
        self.Lista_de_pessoas.setGeometry(QtCore.QRect(261, 15, 201, 143))
        self.Lista_de_pessoas.setObjectName("Lista_de_pessoas")
        self.RE_Cliente = QtWidgets.QFrame(self.centralwidget)
        self.RE_Cliente.setGeometry(QtCore.QRect(0, -20, 501, 341))
        self.RE_Cliente.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.RE_Cliente.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.RE_Cliente.setFrameShadow(QtWidgets.QFrame.Raised)
        self.RE_Cliente.setObjectName("RE_Cliente")
        self.label_7 = QtWidgets.QLabel(self.RE_Cliente)
        self.label_7.setGeometry(QtCore.QRect(10, 40, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.RE_Cliente)
        self.label_8.setGeometry(QtCore.QRect(10, 98, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.RE_Cliente)
        self.label_9.setGeometry(QtCore.QRect(10, 130, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.C_nome = QtWidgets.QLineEdit(self.RE_Cliente)
        self.C_nome.setGeometry(QtCore.QRect(50, 40, 121, 20))
        self.C_nome.setObjectName("C_nome")
        self.C_tel = QtWidgets.QLineEdit(self.RE_Cliente)
        self.C_tel.setGeometry(QtCore.QRect(60, 98, 111, 20))
        self.C_tel.setMaxLength(9)
        self.C_tel.setObjectName("C_tel")
        self.C_lugar = QtWidgets.QLineEdit(self.RE_Cliente)
        self.C_lugar.setGeometry(QtCore.QRect(50, 128, 121, 20))
        self.C_lugar.setObjectName("C_lugar")
        self.BTT_Rcliente = QtWidgets.QPushButton(self.RE_Cliente)
        self.BTT_Rcliente.setGeometry(QtCore.QRect(150, 230, 201, 51))
        self.BTT_Rcliente.setStyleSheet("background-color: rgb(147, 147, 147);\n"
"border-radius: 10px;\n"
"border-radius: 10px;\n"
"font-family: arial;\n"
"font-size:14px;\n"
"text-transform: uppercase;\n"
"font-weight:700;\n"
"")
        self.BTT_Rcliente.setObjectName("BTT_Rcliente")
        self.label_10 = QtWidgets.QLabel(self.RE_Cliente)
        self.label_10.setGeometry(QtCore.QRect(10, 70, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.C_Prefixo = QtWidgets.QComboBox(self.RE_Cliente)
        self.C_Prefixo.setGeometry(QtCore.QRect(55, 70, 118, 20))
        self.C_Prefixo.setObjectName("C_Prefixo")
        self.C_Prefixo.addItem("")
        self.C_Prefixo.addItem("")
        self.C_Prefixo.addItem("")
        self.C_Prefixo.addItem("")
        self.C_Prefixo.addItem("")
        self.PR_clients = QtWidgets.QFrame(self.centralwidget)
        self.PR_clients.setGeometry(QtCore.QRect(-1, -1, 501, 311))
        self.PR_clients.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.PR_clients.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PR_clients.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PR_clients.setObjectName("PR_clients")
        self.listDevendo = QtWidgets.QListWidget(self.PR_clients)
        self.listDevendo.setGeometry(QtCore.QRect(35, 10, 431, 221))
        self.listDevendo.setObjectName("listDevendo")
        self.BTT_Detalhes = QtWidgets.QPushButton(self.PR_clients)
        self.BTT_Detalhes.setGeometry(QtCore.QRect(130, 250, 251, 41))
        self.BTT_Detalhes.setStyleSheet("background-color: rgb(147, 147, 147);\n"
"border-radius: 10px;\n"
"border-radius: 10px;\n"
"font-family: arial;\n"
"font-size:14px;\n"
"text-transform: uppercase;\n"
"font-weight:700;\n"
"")
        self.BTT_Detalhes.setObjectName("BTT_Detalhes")
        self.Detalhe_cliente = QtWidgets.QFrame(self.centralwidget)
        self.Detalhe_cliente.setGeometry(QtCore.QRect(-1, -1, 501, 321))
        self.Detalhe_cliente.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Detalhe_cliente.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Detalhe_cliente.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Detalhe_cliente.setObjectName("Detalhe_cliente")
        self.P_Nome = QtWidgets.QLabel(self.Detalhe_cliente)
        self.P_Nome.setGeometry(QtCore.QRect(10, 20, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.P_Nome.setFont(font)
        self.P_Nome.setObjectName("P_Nome")
        self.P_Telefone = QtWidgets.QLabel(self.Detalhe_cliente)
        self.P_Telefone.setGeometry(QtCore.QRect(10, 50, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.P_Telefone.setFont(font)
        self.P_Telefone.setObjectName("P_Telefone")
        self.P_Lugar = QtWidgets.QLabel(self.Detalhe_cliente)
        self.P_Lugar.setGeometry(QtCore.QRect(10, 80, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.P_Lugar.setFont(font)
        self.P_Lugar.setObjectName("P_Lugar")
        self.linePagar = QtWidgets.QLineEdit(self.Detalhe_cliente)
        self.linePagar.setGeometry(QtCore.QRect(66, 210, 191, 28))
        self.linePagar.setStyleSheet("background-color: rgb(147, 147, 147);\n"
"border-radius: 10px;\n"
"font-family: arial;\n"
"font-size:14px;\n"
"text-transform: uppercase;\n"
"font-weight:700;\n"
"\n"
"")
        self.linePagar.setText("")
        self.linePagar.setObjectName("linePagar")
        self.label_14 = QtWidgets.QLabel(self.Detalhe_cliente)
        self.label_14.setGeometry(QtCore.QRect(26, 214, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(20)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.BTT_Pagar = QtWidgets.QPushButton(self.Detalhe_cliente)
        self.BTT_Pagar.setGeometry(QtCore.QRect(90, 260, 141, 31))
        self.BTT_Pagar.setStyleSheet("background-color: rgb(147, 147, 147);\n"
"border-radius: 10px;\n"
"font-family: arial;\n"
"font-size:14px;\n"
"text-transform: uppercase;\n"
"font-weight:700;\n"
"\n"
"")
        self.BTT_Pagar.setObjectName("BTT_Pagar")
        self.listPendentes = QtWidgets.QListWidget(self.Detalhe_cliente)
        self.listPendentes.setGeometry(QtCore.QRect(305, 40, 181, 241))
        self.listPendentes.setObjectName("listPendentes")
        self.label_15 = QtWidgets.QLabel(self.Detalhe_cliente)
        self.label_15.setGeometry(QtCore.QRect(370, 10, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(14)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.P_Total = QtWidgets.QLabel(self.Detalhe_cliente)
        self.P_Total.setGeometry(QtCore.QRect(380, 290, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.P_Total.setFont(font)
        self.P_Total.setObjectName("P_Total")
        self.Painel1.raise_()
        self.PR_pecas.raise_()
        self.PL_pecas.raise_()
        self.D_Pecas.raise_()
        self.RE_Cliente.raise_()
        self.PR_clients.raise_()
        self.Detalhe_cliente.raise_()
        self.Exit.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 21))
        self.menubar.setObjectName("menubar")
        self.menuTool = QtWidgets.QMenu(self.menubar)
        self.menuTool.setObjectName("menuTool")
        MainWindow.setMenuBar(self.menubar)
        self.actionSalvar = QtWidgets.QAction(MainWindow)
        self.actionSalvar.setObjectName("actionSalvar")
        self.menuTool.addAction(self.actionSalvar)
        self.menubar.addAction(self.menuTool.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.R_cliente.setText(_translate("MainWindow", "Registrar Cliente"))
        self.R_pecas.setText(_translate("MainWindow", "Registrar Peça"))
        self.L_pecas.setText(_translate("MainWindow", "Lista de peças"))
        self.F_pedido.setText(_translate("MainWindow", "Fazer pedido"))
        self.R_conta.setText(_translate("MainWindow", "Revisar contas"))
        self.label.setText(_translate("MainWindow", "Peça"))
        self.label_2.setText(_translate("MainWindow", "Preço"))
        self.label_3.setText(_translate("MainWindow", "Modelo da moto"))
        self.label_4.setText(_translate("MainWindow", "Partileira"))
        self.label_5.setText(_translate("MainWindow", "Mão de obra"))
        self.M_D_Moto.setText(_translate("MainWindow", "All"))
        self.Part.setText(_translate("MainWindow", "Null"))
        self.BTT_peca.setText(_translate("MainWindow", "Registrar"))
        self.label_6.setText(_translate("MainWindow", "Disponiveis"))
        self.Exit.setText(_translate("MainWindow", "X"))
        self.Ver_Detalhe.setText(_translate("MainWindow", "Ver detalhe"))
        self.Excluir.setText(_translate("MainWindow", "Excluir"))
        self.CH_M_D_O.setText(_translate("MainWindow", "Mão de obra"))
        self.Dinhero_final.setText(_translate("MainWindow", "Total: XX,XX"))
        self.Detalhes_peca.setTitle(_translate("MainWindow", "Detalhes"))
        self.D_Peca.setText(_translate("MainWindow", "Peça:"))
        self.D_Modelo.setText(_translate("MainWindow", "Modelo:"))
        self.D_Dispo.setText(_translate("MainWindow", "Disponíveis:"))
        self.D_Preco.setText(_translate("MainWindow", "Preço:"))
        self.D_Part.setText(_translate("MainWindow", "Partileira:"))
        self.BTT_A_Vista.setText(_translate("MainWindow", "A Vista"))
        self.BTT_Fiado.setText(_translate("MainWindow", "Fiado"))
        self.label_7.setText(_translate("MainWindow", "Nome:"))
        self.label_8.setText(_translate("MainWindow", "Telfone:"))
        self.label_9.setText(_translate("MainWindow", "Lugar:"))
        self.BTT_Rcliente.setText(_translate("MainWindow", "Registrar"))
        self.label_10.setText(_translate("MainWindow", "Prefixo:"))
        self.C_Prefixo.setItemText(0, _translate("MainWindow", "71"))
        self.C_Prefixo.setItemText(1, _translate("MainWindow", "73"))
        self.C_Prefixo.setItemText(2, _translate("MainWindow", "74"))
        self.C_Prefixo.setItemText(3, _translate("MainWindow", "75"))
        self.C_Prefixo.setItemText(4, _translate("MainWindow", "77"))
        self.BTT_Detalhes.setText(_translate("MainWindow", "Detalhes"))
        self.P_Nome.setText(_translate("MainWindow", "Nome: XXX"))
        self.P_Telefone.setText(_translate("MainWindow", "Telefone: XXX"))
        self.P_Lugar.setText(_translate("MainWindow", "Lugar: XXX"))
        self.label_14.setText(_translate("MainWindow", "R$"))
        self.BTT_Pagar.setText(_translate("MainWindow", "Pagar"))
        self.label_15.setText(_translate("MainWindow", "Items"))
        self.P_Total.setText(_translate("MainWindow", "Total: "))
        self.menuTool.setTitle(_translate("MainWindow", "Tool"))
        self.actionSalvar.setText(_translate("MainWindow", "Salvar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
